services:
  basic-radio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basic-radio
    ports:
      - 3010:3010
    environment:
      - NODE_ENV=production
      - NUXT_PORT=3010
    restart: always
    networks:
      - basic-network

networks:
  basic-network:
    external: true
